import RequestCard from "./RequestCard"


export default function RequestCards() {
  return (
    <section className="w-9/12 mt-12 flex mx-auto p-3 flex-wrap justify-center">
    <div className="w-1/3 p-2">
      <RequestCard 
      title="POST(CREATING AN ENTITY)"
      url="https://instapi.sinha.website/api/{unique_id}/{endpoint}"
       description="Creating a new entity for a particular endpoint , needs JSON payload"/>
    </div>
    <div className="w-1/3 p-2">
      <RequestCard
      title="GET(GETTING ALL ENTITIES)"
      url="https://instapi.sinha.website/api/{unique_id}/{endpoint}"
      description="Getting all entities for a particular endpoint"
      />
    </div>
    <div className="w-1/3 p-2">
      <RequestCard
      title="GET(GETTING A PARTICULAR ENTITY)"
      url="https://instapi.sinha.website/api/{unique_id}/{endpoint}{_id}"
      description="Getting details of a particular entity , needs _id generated by instapi server"
      idNeeded
      />
    </div>
    <div className="w-1/3 p-2">
      <RequestCard 
      title="PUT(UPDATING A PARTICULAR ENTITY)"
      url="https://instapi.sinha.website/api/{unique_id}/{endpoint}{_id}"
      description="Updating details of a particular entity , needs _id generated by instapi server"
      idNeeded
      />
    </div>
    <div className="w-1/3 p-2">
      <RequestCard
      title="DELETE(DELETING A PARTICULAR ENTITY)"
      url="https://instapi.sinha.website/api/{unique_id}/{endpoint}{_id}"
      description="Deleting  a particular entity , needs _id generated by instapi server"
      idNeeded
      />
    </div>
  </section>
  )
}
