import { useStore } from "../context/StoreContext"
import RequestCard from "./RequestCard"


export default function RequestCards() {

  const {userId} = useStore()

  return (
    <section className="md:w-9/12 mt-12 md:flex md:mx-auto p-3 md:flex-wrap md:justify-center">
    <div className=" lg:w-1/3 p-2 md:w-1/2">
      <RequestCard 
      title="POST(CREATING AN ENTITY)"
      url={`https://instapi.sinha.website/api/${userId}/{endpoint}`}
       description="Creating a new entity for a particular endpoint , needs JSON payload"/>
    </div>
    <div className="sm:w-full lg:w-1/3 p-2 md:w-1/2">
      <RequestCard
      title="GET(GETTING ALL ENTITIES)"
      url={`https://instapi.sinha.website/api/${userId}/{endpoint}`}
      description="Getting all entities for a particular endpoint"
      />
    </div>
    <div className="sm:w-full lg:w-1/3 p-2 md:w-1/2">
      <RequestCard
      title="GET(GETTING A PARTICULAR ENTITY)"
      url={`https://instapi.sinha.website/api/${userId}/{endpoint}/{_id}`}
      description="Getting details of a particular entity , needs _id generated by instapi server"
      isNeeded
      />
    </div>
    <div className="sm:w-full lg:w-1/3 p-2 md:w-1/2">
      <RequestCard 
      title="PUT(UPDATING A PARTICULAR ENTITY)"
      url={`https://instapi.sinha.website/api/${userId}/{endpoint}/{_id}`}
      description="Updating details of a particular entity , needs _id generated by instapi server"
      isNeeded
      />
    </div>
    <div className="sm:w-full lg:w-1/3 p-2 md:w-1/2">
      <RequestCard
      title="DELETE(DELETING A PARTICULAR ENTITY)"
      url={`https://instapi.sinha.website/api/${userId}/{endpoint}/{_id}`}
      description="Deleting  a particular entity , needs _id generated by instapi server"
      isNeeded
      />
    </div>
  </section>
  )
}
